name: Pay By Phone CI
on:
  push:
    paths:
      - 'pay-by-phone/**'

defaults:
  run:
    working-directory: pay-by-phone

jobs:
  self_service_1_5:
    name: Pay By Phone
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version`: [12.x, 14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Static Code Analysis
        run: yarn lint
      - name: Test
        run: yarn test:cov
        env:
          AUTH_TOKEN: "N/A"
          ACCOUNT_ID: "N/A"
          APPLICATION_ID: "N/A"
          FC_NUMBER: "N/A"
          PORT: "3000"
          HOST: "http://localhost:3000"
