name: Push to Docker Hub

on:
  push:
    branches:
      - [master, code, test]


jobs:
  pay-by-phone:
    name: Build & Push Pay By Phone
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./pay-by-phone/Dockerfile
          context: ./pay-by-phone
          tags: freeclimbapi/pay-by-phone:latest
          push: true

